/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megasena;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JCheckBox;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author cleit
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    /**
     * Atribuos privados
     */
    private static int marcaçõesRestantes, qtdeMarcaçõesFeitas = 0;
    private static int qtdeNúmerosSelecionados;
    private static final HashSet<Integer> numSelecionados = new HashSet<>();
    private static final ArrayList<JCheckBox> listaCheckBoxes = new ArrayList<>();
    private static ArrayList<Integer> numSorteados = new ArrayList<>();
    private static final ArrayList<Integer> acertos = new ArrayList<>();
    private static Sena sena;
    
    /**
     * Construtor
     */
    public FramePrincipal() {
        super();
        
        // Inicializa componentes
        initComponents();
        
        // Icializa o singleton
        sena = new Sena();
        
        // Inicializar a lista de check boxes
        for (Component c : jPanelCartela.getComponents()) {
            if (c instanceof JCheckBox) { 
                listaCheckBoxes.add((JCheckBox) c);
            }
        }
        
        // Adiciona tratadores de envento aos jCheckBox
        CheckBoxHandler handler = new CheckBoxHandler();
        listaCheckBoxes.stream().forEach(jCheckBox -> {
            jCheckBox.addActionListener(handler);
        }); 
        
        // inicialia variáveis
        qtdeNúmerosSelecionados = Integer.parseInt(cmbQtdeNúmeros.getSelectedItem().toString());
        marcaçõesRestantes =  qtdeNúmerosSelecionados;
        atualizaMarcaçõesRestantes();
        
        // limpa e atualiza os labels
        limpaFormulário();
    } // Construtor
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTítulo = new javax.swing.JLabel();
        jPanelAposta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbQtdeNúmeros = new javax.swing.JComboBox<>();
        jCheckBoxSurpresinha = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanelProbabilidades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblProbablidadeSena = new javax.swing.JLabel();
        lblProbablidadeQuina = new javax.swing.JLabel();
        lblProbablidadeQuadra = new javax.swing.JLabel();
        jPanelCartela = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        lblMarcaçõesRestantes = new javax.swing.JLabel();
        jPanelSorteio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelAposta = new javax.swing.JLabel();
        jLabelNúmerosSorteados = new javax.swing.JLabel();
        jLabelAcertos = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonApostar = new javax.swing.JButton();
        jButtonTeimosinha = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador da Mega Sena v0.8");
        setName(""); // NOI18N
        setResizable(false);

        jLabelTítulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTítulo.setText("Teste sua sorte!");

        jPanelAposta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aposta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Quantidade de números:");

        cmbQtdeNúmeros.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbQtdeNúmeros.setMaximumRowCount(3);
        cmbQtdeNúmeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cmbQtdeNúmeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQtdeNúmerosActionPerformed(evt);
            }
        });

        jCheckBoxSurpresinha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxSurpresinha.setBorder(null);
        jCheckBoxSurpresinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSurpresinhaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Supresinha:");

        javax.swing.GroupLayout jPanelApostaLayout = new javax.swing.GroupLayout(jPanelAposta);
        jPanelAposta.setLayout(jPanelApostaLayout);
        jPanelApostaLayout.setHorizontalGroup(
            jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApostaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbQtdeNúmeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSurpresinha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelApostaLayout.setVerticalGroup(
            jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApostaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbQtdeNúmeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBoxSurpresinha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProbabilidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Probabilidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Sena:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Quina:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Quadra:");

        lblProbablidadeSena.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblProbablidadeSena.setText("lblProbSena");

        lblProbablidadeQuina.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblProbablidadeQuina.setText("lblProbQuina");

        lblProbablidadeQuadra.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblProbablidadeQuadra.setText("lblProbQuadra");

        javax.swing.GroupLayout jPanelProbabilidadesLayout = new javax.swing.GroupLayout(jPanelProbabilidades);
        jPanelProbabilidades.setLayout(jPanelProbabilidadesLayout);
        jPanelProbabilidadesLayout.setHorizontalGroup(
            jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProbabilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProbablidadeQuadra)
                    .addComponent(lblProbablidadeQuina)
                    .addComponent(lblProbablidadeSena))
                .addContainerGap())
        );
        jPanelProbabilidadesLayout.setVerticalGroup(
            jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProbabilidadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblProbablidadeSena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblProbablidadeQuina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProbabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblProbablidadeQuadra))
                .addContainerGap())
        );

        jPanelCartela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanelCartela.setName(""); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox1.setText("01");

        jCheckBox2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox2.setText("02");

        jCheckBox4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox4.setText("04");

        jCheckBox5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox5.setText("05");

        jCheckBox6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox6.setText("06");

        jCheckBox7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox7.setText("07");

        jCheckBox8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox8.setText("08");

        jCheckBox9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setText("09");

        jCheckBox10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox10.setText("10");

        jCheckBox11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox11.setText("11");

        jCheckBox12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox12.setText("12");

        jCheckBox13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox13.setText("13");

        jCheckBox14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox14.setText("14");

        jCheckBox15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox15.setText("15");

        jCheckBox16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox16.setText("16");

        jCheckBox17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox17.setText("17");

        jCheckBox18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox18.setText("18");

        jCheckBox19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox19.setText("19");

        jCheckBox20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox20.setText("20");

        jCheckBox21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox21.setText("21");

        jCheckBox22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox22.setText("22");

        jCheckBox23.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox23.setText("23");

        jCheckBox24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox24.setText("24");

        jCheckBox25.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox25.setText("25");

        jCheckBox26.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox26.setText("26");

        jCheckBox27.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox27.setText("27");

        jCheckBox28.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox28.setText("28");

        jCheckBox29.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox29.setText("29");

        jCheckBox30.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox30.setText("30");

        jCheckBox31.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox31.setText("31");

        jCheckBox32.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox32.setText("32");

        jCheckBox33.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox33.setText("33");

        jCheckBox34.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox34.setText("34");

        jCheckBox35.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox35.setText("35");

        jCheckBox36.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox36.setText("36");

        jCheckBox37.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox37.setText("37");

        jCheckBox38.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox38.setText("38");

        jCheckBox39.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox39.setText("39");

        jCheckBox40.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox40.setText("40");

        jCheckBox41.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox41.setText("41");

        jCheckBox42.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox42.setText("42");

        jCheckBox43.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox43.setText("43");

        jCheckBox44.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox44.setText("44");

        jCheckBox45.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox45.setText("45");

        jCheckBox46.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox46.setText("46");

        jCheckBox47.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox47.setText("47");

        jCheckBox48.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox48.setText("48");

        jCheckBox49.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox49.setText("49");

        jCheckBox50.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox50.setText("50");

        jCheckBox51.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox51.setText("51");

        jCheckBox52.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox52.setText("52");

        jCheckBox53.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox53.setText("53");

        jCheckBox54.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox54.setText("54");

        jCheckBox55.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox55.setText("55");

        jCheckBox56.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox56.setText("56");

        jCheckBox57.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox57.setText("57");

        jCheckBox58.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox58.setText("58");

        jCheckBox59.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox59.setText("59");

        jCheckBox60.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox60.setText("60");

        jCheckBox3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox3.setText("03");

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel7.setText("Marcações restantes:");

        lblMarcaçõesRestantes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblMarcaçõesRestantes.setText("jLabel8");

        javax.swing.GroupLayout jPanelCartelaLayout = new javax.swing.GroupLayout(jPanelCartela);
        jPanelCartela.setLayout(jPanelCartelaLayout);
        jPanelCartelaLayout.setHorizontalGroup(
            jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCartelaLayout.createSequentialGroup()
                        .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox10))
                            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                                .addComponent(jCheckBox11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox20))
                            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                                .addComponent(jCheckBox21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox30))
                            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                                .addComponent(jCheckBox31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox40))
                            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                                .addComponent(jCheckBox41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox50))
                            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                                .addComponent(jCheckBox51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox60)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanelCartelaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMarcaçõesRestantes)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelCartelaLayout.setVerticalGroup(
            jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox22)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox24)
                    .addComponent(jCheckBox25)
                    .addComponent(jCheckBox26)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox28)
                    .addComponent(jCheckBox29)
                    .addComponent(jCheckBox30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox31)
                    .addComponent(jCheckBox32)
                    .addComponent(jCheckBox33)
                    .addComponent(jCheckBox34)
                    .addComponent(jCheckBox35)
                    .addComponent(jCheckBox36)
                    .addComponent(jCheckBox37)
                    .addComponent(jCheckBox38)
                    .addComponent(jCheckBox39)
                    .addComponent(jCheckBox40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox41)
                    .addComponent(jCheckBox42)
                    .addComponent(jCheckBox43)
                    .addComponent(jCheckBox44)
                    .addComponent(jCheckBox45)
                    .addComponent(jCheckBox46)
                    .addComponent(jCheckBox47)
                    .addComponent(jCheckBox48)
                    .addComponent(jCheckBox49)
                    .addComponent(jCheckBox50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox51)
                    .addComponent(jCheckBox52)
                    .addComponent(jCheckBox53)
                    .addComponent(jCheckBox54)
                    .addComponent(jCheckBox55)
                    .addComponent(jCheckBox56)
                    .addComponent(jCheckBox57)
                    .addComponent(jCheckBox58)
                    .addComponent(jCheckBox59)
                    .addComponent(jCheckBox60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCartelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMarcaçõesRestantes)))
        );

        jPanelSorteio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sorteio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Sua aposta:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Números sorteados:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Resultado:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Acertos:");

        jLabelAposta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelAposta.setText("lblAposta");

        jLabelNúmerosSorteados.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelNúmerosSorteados.setText("lblNúmerosSorteados");

        jLabelAcertos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelAcertos.setText("lblAcertos");

        jLabelResultado.setText("lblResultado");

        javax.swing.GroupLayout jPanelSorteioLayout = new javax.swing.GroupLayout(jPanelSorteio);
        jPanelSorteio.setLayout(jPanelSorteioLayout);
        jPanelSorteioLayout.setHorizontalGroup(
            jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSorteioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAcertos)
                    .addComponent(jLabelAposta)
                    .addComponent(jLabelResultado)
                    .addComponent(jLabelNúmerosSorteados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSorteioLayout.setVerticalGroup(
            jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSorteioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAposta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNúmerosSorteados)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabelAcertos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResultado)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonApostar.setText("Apostar");
        jButtonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarActionPerformed(evt);
            }
        });

        jButtonTeimosinha.setText("Teimosinha");
        jButtonTeimosinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeimosinhaActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanelAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelProbabilidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelCartela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSorteio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonApostar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTeimosinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabelTítulo)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTítulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProbabilidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCartela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApostar)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonTeimosinha))
                .addGap(42, 42, 42))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpa todos os componentes do formulário
     */
    private void limpaFormulário(){
        
        // Limpa as marcações
        listaCheckBoxes.stream().forEach(jCheckBox -> {
                jCheckBox.setSelected(false);
                Font plainFont = new Font("Dialog", Font.PLAIN, 12);
                jCheckBox.setFont(plainFont);
                jCheckBox.setForeground(Color.black);
            }
        );
        
        // reinicializa variáveis auxiliares
        numSelecionados.clear();
        qtdeMarcaçõesFeitas = 0;
        
        if (jCheckBoxSurpresinha.isSelected()==false){
            atualizaMarcaçõesRestantes();
        }
        // limpa e a atualiza os labels
        jLabelAposta.setText("");
        atualizaProbabilidade();
        jLabelNúmerosSorteados.setText("");
        jLabelAcertos.setText("");
        jLabelResultado.setText("");
    }
    
    /**
     * Atualiza o número de marcações restantes para finalizar aposta;
     */
    private void atualizaMarcaçõesRestantes(){
        marcaçõesRestantes = qtdeNúmerosSelecionados - qtdeMarcaçõesFeitas;  
        lblMarcaçõesRestantes.setText(Integer.toString(marcaçõesRestantes));

        if (marcaçõesRestantes == 0) {
            jButtonApostar.setEnabled(true);
            jButtonTeimosinha.setEnabled(true);
        }
        else {
            jButtonApostar.setEnabled(false);
            jButtonTeimosinha.setEnabled(false);
        } 
    }
    
    /**
     * Atualiza a visualização dos números acertados
     */
    private void mostraAcertos(ArrayList<Integer> acertos){
        int qtdeAcertos = acertos.size();
        String resultado;
        switch (qtdeAcertos){
            case 0:
                resultado = "Chuta que é urucubaca";
                break;
            case 1:
                resultado = "Você acertou 1 número";
                break;
            case 4:
                resultado = "Parabéns, você acertou a quadra!";
                break;
            case 5:
                resultado = "Parabéns, você acertou a quina!";
                break;
            case 6:
                resultado = "PARABÉNS, VOCÊ AGORA É MILIONÁRIO!";
                break;
            default:
                resultado = "Você acertou "+qtdeAcertos+" números";
                break;
        }
        jLabelResultado.setText(resultado);
        
        // Marca os acertos em azul em caso de não supresinha
        if ((qtdeAcertos>0) && (jCheckBoxSurpresinha.isSelected()==false)){
            acertos.stream().forEach(acerto -> {
                listaCheckBoxes.get(acerto-1).setForeground(Color.blue);
            });
        } // if (qrdeAcertos>0)
        jLabelAcertos.setText(acertos.toString());
    } // private void mostraAcertos

    /**
     * Remove formatação de números acertados 
     */
    private void limpaAcertosAnteriores(){
        
        // Re-marca os números selecionados em vermelho em caso de não-surpresinha
        if ((acertos.size()>0) && (jCheckBoxSurpresinha.isSelected()==false)){
            numSelecionados.stream().forEach(num -> {
                listaCheckBoxes.get(num-1).setForeground(Color.red);
            });
            
        }
        // limpa a lista de acertos
        acertos.clear();
        jLabelAcertos.setText("");
    }
    
    private void atualizaProbabilidade(){
        long probabilidadeSena = Sena.calculaProbabilidade(qtdeNúmerosSelecionados,6);
        long probabilidadeQuina = Sena.calculaProbabilidade(qtdeNúmerosSelecionados,5);
        long probabilidadeQuadra = Sena.calculaProbabilidade(qtdeNúmerosSelecionados,4);
        DecimalFormat df = new DecimalFormat("###,###,###");
        lblProbablidadeSena.setText("1 em "+df.format(probabilidadeSena));
        lblProbablidadeQuina.setText("1 em "+df.format(probabilidadeQuina));
        lblProbablidadeQuadra.setText("1 em "+df.format(probabilidadeQuadra));
    }
    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarActionPerformed
 
        // Sorteia os números em caso de Surpresinha
        if (jCheckBoxSurpresinha.isSelected()){
            numSelecionados.clear();
            numSelecionados.addAll(sena.sorteiaNumeros(qtdeNúmerosSelecionados));
        }

        // Mostra os números selecionados
        ArrayList<Integer> selecionados = new ArrayList<>(numSelecionados);
        Collections.sort(selecionados);
        jLabelAposta.setText(selecionados.toString());
        
        // Limpa os acertos anteriores
        limpaAcertosAnteriores();
         
        // Sorteia os números da Mega-Sena
        numSorteados = sena.sorteiaNumeros(6);
        jLabelNúmerosSorteados.setText(numSorteados.toString());
        
        // Identifica os números que foram acertados
        for (int i=0; i<6;i++){
            if (numSelecionados.contains(numSorteados.get(i)))
                acertos.add(numSorteados.get(i));
        }
       
        // Mostra os números acertados
        mostraAcertos(acertos);
    }//GEN-LAST:event_jButtonApostarActionPerformed
   
    private void cmbQtdeNúmerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQtdeNúmerosActionPerformed
        qtdeNúmerosSelecionados = Integer.parseInt(cmbQtdeNúmeros.getSelectedItem().toString());
        
        if (jCheckBoxSurpresinha.isSelected()== false){
            if (qtdeNúmerosSelecionados >= qtdeMarcaçõesFeitas)
                atualizaMarcaçõesRestantes();
            else
                limpaFormulário();
        }
        
        // Atutaliza a probabilidade
        atualizaProbabilidade();
        
    }//GEN-LAST:event_cmbQtdeNúmerosActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limpaFormulário();
    }//GEN-LAST:event_jButtonLimparActionPerformed
 
    
    private void jButtonTeimosinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeimosinhaActionPerformed
        
        DialogTeimosinha dialogOpçõesForçar = new DialogTeimosinha(this, true);
        dialogOpçõesForçar.setVisible(true);
        int numAcertosDesejados = dialogOpçõesForçar.opçãoSelecionada;
        
        if (numAcertosDesejados != 0) {
            
            // Sorteia os números em caso de Surpresinha
            if (jCheckBoxSurpresinha.isSelected()){
                numSelecionados.clear();
                numSelecionados.addAll(sena.sorteiaNumeros(qtdeNúmerosSelecionados));
            }

            // Mostra os números selecionados
            ArrayList<Integer> selecionados = new ArrayList<>(numSelecionados);
            Collections.sort(selecionados);
            jLabelAposta.setText(selecionados.toString());

            // Limpa os acertos anteriores
            limpaAcertosAnteriores();

            // Sorteia os números da Mega-Sena
            int numJogosRealizados =0;
            int quadras = 0;
            int quinas = 0;
            while ((acertos.size()< numAcertosDesejados) && (numJogosRealizados < 5300 )){
                limpaAcertosAnteriores();
                numSorteados = sena.sorteiaNumeros(6);

                for (int i=0; i<6;i++){
                    if (numSelecionados.contains(numSorteados.get(i)))
                        acertos.add(numSorteados.get(i));
                }
                numJogosRealizados++;
                if (acertos.size()==4)
                    quadras++;
                else if (acertos.size()==5)
                    quinas++;
            }
            jLabelNúmerosSorteados.setText(numSorteados.toString());

            // Mostra os números acertados
            mostraAcertos(acertos);
            if (numJogosRealizados == 5300)
                JOptionPane.showMessageDialog(rootPane, "Passaram-se 100 anos e você não ganhou!\n"+
                        "Número de quadras: "+quadras+
                        "\nNúmero de quinas: "+quinas);
            else
                JOptionPane.showMessageDialog(rootPane, "Você atingiu o objetivo após " + numJogosRealizados + " jogos\n"+
                        "Número de quadras: "+quadras+
                        "\nNúmero de quinas: "+quinas);
        }
    }//GEN-LAST:event_jButtonTeimosinhaActionPerformed

    private void jCheckBoxSurpresinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSurpresinhaActionPerformed
        
        JCheckBox jCheckBox;
        jCheckBox = (JCheckBox) evt.getSource();
        
        limpaFormulário();
        if (jCheckBox.isSelected()){         
            // Desabilita os checkBox
            listaCheckBoxes.stream().forEach(checkBox -> {
                checkBox.setEnabled(false);
            });
            // Desabilita os labels de números restantes
            lblMarcaçõesRestantes.setText("");

            // Habilita a aposta
            jButtonApostar.setEnabled(true);
            jButtonTeimosinha.setEnabled(true);
            
        } else {
            // Habilita os checkBox
            listaCheckBoxes.stream().forEach(checkBox -> {
                checkBox.setEnabled(true); 
            });
            // Desabilita a aposta
            jButtonApostar.setEnabled(false);
            jButtonTeimosinha.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxSurpresinhaActionPerformed

    private class CheckBoxHandler implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent event){
            JCheckBox jCheckBox;
            jCheckBox = (JCheckBox) event.getSource();

                if (jCheckBox.isSelected()){
                    if (marcaçõesRestantes > 0){
                        jCheckBox.setForeground(Color.red);
                        Font boldFont = new Font("Dialog", Font.BOLD, 12);
                        jCheckBox.setFont(boldFont);
                        numSelecionados.add(Integer.parseInt(jCheckBox.getText()));
                        qtdeMarcaçõesFeitas++;
                    } else {
                        jCheckBox.setSelected(false);
                       // JOptionPane.showMessageDialog(rootPane, "Você selecionou mais números do que o definido para esta aposta");
                    }
                       
                } else {
                    Font plainFont = new Font("Dialog", Font.PLAIN, 12);
                    jCheckBox.setFont(plainFont);
                    jCheckBox.setForeground(Color.black);
                    numSelecionados.remove(Integer.parseInt(jCheckBox.getText()));        
                    qtdeMarcaçõesFeitas--;
                }              
                atualizaMarcaçõesRestantes();      
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbQtdeNúmeros;
    private javax.swing.JButton jButtonApostar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTeimosinha;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBox jCheckBoxSurpresinha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAcertos;
    private javax.swing.JLabel jLabelAposta;
    private javax.swing.JLabel jLabelNúmerosSorteados;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelTítulo;
    private javax.swing.JPanel jPanelAposta;
    private javax.swing.JPanel jPanelCartela;
    private javax.swing.JPanel jPanelProbabilidades;
    private javax.swing.JPanel jPanelSorteio;
    private javax.swing.JLabel lblMarcaçõesRestantes;
    private javax.swing.JLabel lblProbablidadeQuadra;
    private javax.swing.JLabel lblProbablidadeQuina;
    private javax.swing.JLabel lblProbablidadeSena;
    // End of variables declaration//GEN-END:variables
}
